[build]
  publish = "astro/astrowind/dist/client"
  command = "npm --workspace @wix/astrowind-template run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
